name = "WJFParallelTask"
uuid = "e651f0bd-5ae6-4ed7-94b7-345472aabd1c"
authors = ["wujunfeng1 <59754256+wujunfeng1@users.noreply.github.com>"]
version = "0.1.15"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
